apiVersion: v1
kind: Secret
type: Opaque
metadata:
  creationTimestamp: "2019-03-28T06:25:02Z"
  name: drone-k8s-secrets
  namespace: devops-cicd
  annotations:
    X-Drone-Repos: jenkins/*,cloud/*
    X-Drone-Events: push,tag
data:
  password: 
  token: 
  url: 
  username: 

