apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-kubernetes-secrets
  namespace: devops-cicd
  labels:
    app: drone-kubernetes-secrets
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: drone-kubernetes-secrets
  template:
    metadata:
      labels: 
        app: drone-kubernetes-secrets
    spec:
      serviceAccountName: secret-reader 
      containers:
      - name: drone-kubernetes-secrets
        image: drone/kubernetes-secrets
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        #volumeMounts:
        #- mountPath: /etc/kubernetes/config
        #  name: kube-config
        env: 
          - name: SECRET_KEY
            value: 1b8e384d
          #- name: KUBERNETES_CONFIG
          #  value: /etc/kubernetes/config
          - name: DEBUG
            value: "1"
          - name: KUBERNETES_NAMESPACE
            value: "devops-cicd"
     # nodeSelector:
     #   kubernetes.io/hostname: node01
     # volumes:
     # - name: kube-config
     #   hostPath:
     #     path: /opt/kube/config
     #     type: File

---

apiVersion: v1
kind: Service
metadata: 
  name: drone-kubernetes-secrets
  namespace: devops-cicd
  labels: 
    name: drone-kubernetes-secrets
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector: 
    app: drone-kubernetes-secrets
